# Generated by Django 3.2.6 on 2021-08-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_auto_20210817_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PlatformName', max_length=30)),
                ('link', models.CharField(default='Social Link', max_length=150)),
                ('icon', models.CharField(blank=True, default='fas fa-user-friends', max_length=60)),
            ],
        ),
    ]
