# Generated by Django 3.2.6 on 2021-08-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='short_message',
            field=models.TextField(max_length=110),
        ),
        migrations.AlterField(
            model_name='profile',
            name='welcome_message',
            field=models.TextField(max_length=60),
        ),
    ]
