# Generated by Django 3.2.6 on 2021-08-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_socialplatforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='avatar.bmp', upload_to='profile_pics'),
        ),
    ]
