# Generated by Django 3.2.6 on 2021-09-20 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='User Name', max_length=70)),
                ('location', models.CharField(default='Chicago', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WordedIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_type', models.CharField(choices=[('SOCIAL_MEDIA', 'Social Media'), ('GENERAL_DATA', 'General Data'), ('SOFT_SKILL', 'Soft skill'), ('TECHNICAL_SKILL', 'Technical Skill')], default='SOCIAL_MEDIA', max_length=50)),
                ('url_link', models.URLField(blank=True)),
                ('icon_name', models.CharField(default='Worded Icon Name', max_length=50)),
                ('primary_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
    ]
