# Generated by Django 3.2.6 on 2021-09-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='User Name', max_length=70)),
                ('location', models.CharField(default='Chicago', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Worded Icon Name', max_length=50)),
                ('description', models.CharField(blank=True, max_length=80)),
                ('url_link', models.URLField(blank=True)),
                ('ft_awesome_name', models.CharField(default='fas fa-atom', max_length=70)),
                ('icon_type', models.CharField(choices=[('SOCIAL_MEDIA', 'Social Media'), ('GENERAL_DATA', 'General Data')], default='SOCIAL_MEDIA', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('skill_type', models.CharField(choices=[('SOFT_SKILL', 'Soft skill'), ('TECHNICAL_SKILL', 'Technical Skill')], default='SOFT_SKILL', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='wordedicon',
            name='primary_key',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.DeleteModel(
            name='WordedIcon',
        ),
    ]
