# Generated by Django 3.2.6 on 2021-09-20 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210920_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=80)),
                ('period_range', models.CharField(max_length=50)),
                ('event_type', models.CharField(choices=[('PROJECT', 'Project'), ('WORK', 'Work')], default='PROJECT', max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.CreateModel(
            name='EventDutie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_description', models.TextField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.event')),
            ],
        ),
    ]
