# Generated by Django 3.2.6 on 2021-09-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20210920_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(default='fas fa-atom', max_length=50),
        ),
    ]
