# Generated by Django 3.2.6 on 2021-09-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20210920_1915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dutie',
            new_name='Duty',
        ),
    ]
