# Generated by Django 3.2.6 on 2021-09-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_educationalinstitution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Duty',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
