# Generated by Django 3.2.6 on 2021-10-03 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_rename_genericlinks_genericlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.genericinformation')),
            ],
        ),
        migrations.DeleteModel(
            name='ExternalLink',
        ),
        migrations.DeleteModel(
            name='GenericLink',
        ),
    ]
