# Generated by Django 3.2.6 on 2021-10-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_auto_20211003_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericinformation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='genericinformation',
            name='location',
        ),
    ]
