# Generated by Django 3.2.6 on 2021-09-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Project', max_length=50)),
                ('link', models.CharField(default='Github Link', max_length=200)),
            ],
        ),
    ]
